### ISSUE TITLE
Panics when typing or clearing a character if no results match the search

### ISSUE THREAD

**Issue by bash** [zeenix/gimoji#169]
Getting the panic message requires redirecting stderr to a file:

```shell
sh$ cargo run 2>stderr.txt
# enter "foo", no emojis match this query so the list is empty
# either press backspace or enter another character
# <exits>
sh$ echo $? # prints the exit code
sh$ cat stderr.txt
   Compiling gimoji v1.1.0 (/.../gimoji)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.41s
     Running `target/debug/gimoji`
thread 'main' panicked at src/selection_view.rs:40:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zeenix** [comment]
> ```shell
> # enter "foo", no emojis match this query so the list is empty
> # either press backspace or enter another character
> # <exits>
> ```

I'm not sure I quite follow how to reproduce. How does the `<exit>` happen? Also if you press backspace after `foo`, you get `fo` and that matches 3 emojis.

**Comment by zeenix** [comment]
> You have to enter _just_ enough characters to cause the emoji list to be empty. Then you can either hit backspace (which would mean that the list would become non-empty again) or type another character.

I did that but I was unable to reproduce the issue.
