### ISSUE TITLE
On Mac git hook does not work

### ISSUE THREAD

**Issue by rimbi** [zeenix/gimoji#20]
The hook ends up with the following output:

```bash
+ exec
+ gimoji --hook .git/COMMIT_EDITMSG
Error: Custom { kind: Other, error: "Failed to initialize input reader" }
```

**Comment by zeenix** [comment]
Thanks for reporting this. I was wondering about that. Can you check if removing the exec line in the hook file (`.git/hooks/prepare-commit-msg`) helps?

**Comment by zeenix** [comment]
> Thanks for reporting this. I was wondering about that. Can you check if removing the exec line in the hook file (`.git/hooks/prepare-commit-msg`) helps?

Created #21 as a potential fix.
