### ISSUE TITLE
Integration with commit alias

### ISSUE THREAD

**Issue by syepes** [zeenix/gimoji#32]
Very nice tool, but woudl you know how irt would be integrated into when using the following alias?

git cm "some message"

```
[alias]
 cm = commit -a -m
```

**Comment by zeenix** [comment]
Hi. Thanks. 

Aliasing has no effect here but `-m` means the user already provides the commit message and currently the tool gets out of your way when that's the case.

However, I'm myself finding that annoying so I'm thinking of adding detection of emoji prefix and when no emoji is detected, the tool does its job.
