### ISSUE TITLE
"Copy to clipboard" doesn't  work

### ISSUE THREAD

**Issue by MaxVerevkin** [zeenix/gimoji#34]
This patch does not fix it: 

```diff
diff --git a/Cargo.toml b/Cargo.toml
index ec6afbb..6e825eb 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ clap = { version = "4.3.0", features = ["derive"] }
 crossterm = { version = "0.26.1", features = ["use-dev-tty"] }
 ratatui = "0.21.0"
 regex = { version = "1.8.2", default-features = false, features = ["std", "perf", "unicode-case" ] }
-arboard = { version = "3.2.0", default-features = false }
+arboard = { version = "3.2.0", default-features = false, features = ["wayland-data-control"] }
 
 [build-dependencies]
 serde = { version = "1.0.163", features = ["derive"] }
```

**Comment by zeenix** [comment]
>  "Copy to clipboard" doesn't work on Wayland #34 

I'm on wayland too (Fedora), and it works flawlessly. Are you sure wayland is the issue?

**Comment by MaxVerevkin** [comment]
Huh, I just tried xorg (i3) it doesn't work either...

**Comment by zeenix** [comment]
> Huh, I just tried xorg (i3) it doesn't work either...

Works both on my Fedora and Ubuntu machines. People hare reported it to work on Mac too. Perhaps your DE is the problem here?

In any case, we rely completely on arboard for this so if it doesn't work, it's mostly likely a limitation/bug in arboard.

**Comment by zeenix** [comment]
> I tested three WMs: river (wayland), hyprland (wayland) and i3 (xorg). None if them seem to wrok...

Something is definitely up with your system:

```
❯ gimoji 
Copied 🎨 to the clipboard
❯ wl-paste                                                                                                                                                                                                                                                                                                                                               
🎨 
```

**Comment by zeenix** [comment]
> I tested three WMs: river (wayland), hyprland (wayland) and i3 (xorg).

I've not even heard of the first 2. :) Can't you use something normal, like GNOME or even KDE? :)

**Comment by MaxVerevkin** [comment]
> Something is definitely up with your system:

I don't think so, this is the first program that has any issues with the clipboard. The `arboard` docs actually explain what is going on:

> [Linux](https://docs.rs/arboard/latest/arboard/struct.Clipboard.html#linux)
>
> Using either Wayland and X11, the clipboard and its content is “hosted” inside of the application that last put data onto it. This means that when the last Clipboard instance is dropped, the contents may become unavailable to other apps. See [SetExtLinux](https://docs.rs/arboard/latest/arboard/trait.SetExtLinux.html) for more details.

and

> Whether to wait for the clipboard’s contents to be replaced after setting it.
>
> The Wayland and X11 clipboards work by having the clipboard content being, at any given time, “owned” by a single process, and that process is expected to reply to all the requests from any other system process that wishes to access the clipboard’s contents. As a consequence, when that process exits the contents of the clipboard will effectively be cleared since there is no longer anyone around to serve requests for it.
>
> This poses a problem for short-lived programs that just want to copy to the clipboard and then exit, since they don’t want to wait until the user happens to copy something else just to finish. To resolve that, whenever the user copies something you can offload the actual work to a newly-spawned daemon process which will run in the background (potentially outliving the current process) and serve all the requests. That process will then automatically and silently exit once the user copies something else to their clipboard so it doesn’t take up too many resources.
>
> To support that pattern, this method will not only have the contents of the clipboard be set, but will also wait and continue to serve requests until the clipboard is overwritten. As long as you don’t exit the current process until that method has returned, you can avoid all surprising situations where the clipboard’s contents seemingly disappear from under your feet.
>
> See the [daemonize example](https://github.com/1Password/arboard/blob/master/examples/daemonize.rs) for a demo of how you could implement this.

**Comment by MaxVerevkin** [comment]
This patch "fixes" the issue but only if a clipboard manager (like `clipmon`) is running:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index ec6afbb..6e825eb 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ clap = { version = "4.3.0", features = ["derive"] }
 crossterm = { version = "0.26.1", features = ["use-dev-tty"] }
 ratatui = "0.21.0"
 regex = { version = "1.8.2", default-features = false, features = ["std", "perf", "unicode-case" ] }
-arboard = { version = "3.2.0", default-features = false }
+arboard = { version = "3.2.0", default-features = false, features = ["wayland-data-control"] }
 
 [build-dependencies]
 serde = { version = "1.0.163", features = ["derive"] }
diff --git a/src/main.rs b/src/main.rs
index c0bf1c5..7d71b7b 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -10,7 +10,7 @@ use clap::{command, Parser};
 use crossterm::event::{read, Event, KeyCode};
 use ratatui::layout::{Constraint, Layout};
 use selection_view::SelectionView;
-use std::{error::Error, fs::File, io::Write};
+use std::{error::Error, fs::File, io::Write, time::Duration};
 #[cfg(unix)]
 use std::{fs::Permissions, os::unix::prelude::PermissionsExt};
 
@@ -73,6 +73,7 @@ fn main() -> Result<(), Box<dyn Error>> {
         file.write_all(prefix.as_bytes())?;
     } else {
         Clipboard::new()?.set_text(&selected)?;
+        std::thread::sleep(Duration::from_millis(100));
         println!("Copied {} to the clipboard", selected);
     }
 
```

**Comment by MaxVerevkin** [comment]
I think this is a proper fix:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index ec6afbb..ccf0fba 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,8 @@ clap = { version = "4.3.0", features = ["derive"] }
 crossterm = { version = "0.26.1", features = ["use-dev-tty"] }
 ratatui = "0.21.0"
 regex = { version = "1.8.2", default-features = false, features = ["std", "perf", "unicode-case" ] }
-arboard = { version = "3.2.0", default-features = false }
+arboard = { version = "3.2.0", default-features = false, features = ["wayland-data-control"] }
+nix = { version = "0.26", default-features = false, features = ["process"] }
 
 [build-dependencies]
 serde = { version = "1.0.163", features = ["derive"] }
diff --git a/src/main.rs b/src/main.rs
index c0bf1c5..e2d0604 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -10,7 +10,7 @@ use clap::{command, Parser};
 use crossterm::event::{read, Event, KeyCode};
 use ratatui::layout::{Constraint, Layout};
 use selection_view::SelectionView;
-use std::{error::Error, fs::File, io::Write};
+use std::{error::Error, fs::File, io::Write, time::Duration};
 #[cfg(unix)]
 use std::{fs::Permissions, os::unix::prelude::PermissionsExt};
 
@@ -72,8 +72,8 @@ fn main() -> Result<(), Box<dyn Error>> {
         let prefix = format!("{} ", selected);
         file.write_all(prefix.as_bytes())?;
     } else {
-        Clipboard::new()?.set_text(&selected)?;
-        println!("Copied {} to the clipboard", selected);
+        println!("Copied {selected} to the clipboard");
+        copy_to_clipboard(selected);
     }
 
     Ok(())
@@ -140,6 +140,26 @@ fn install_hook() -> Result<(), Box<dyn Error>> {
     Ok(())
 }
 
+#[cfg(all(
+    unix,
+    not(any(target_os = "macos", target_os = "android", target_os = "emscripten")),
+))]
+fn copy_to_clipboard(s: String) -> Result<(), Box<dyn Error>> {
+    use arboard::SetExtLinux;
+    nix::unistd::daemon(false, false)?;
+    Clipboard::new()?.set().wait().text(s)?;
+    Ok(())
+}
+
+#[cfg(not(all(
+    unix,
+    not(any(target_os = "macos", target_os = "android", target_os = "emscripten")),
+)))]
+fn copy_to_clipboard(s: String) -> Result<(), Box<dyn Error>> {
+    Clipboard::new()?.set().text(s)?;
+    Ok(())
+}
+
 const HOOK_PATH: &str = ".git/hooks/prepare-commit-msg";
 const HOOK_CONTENT: &str = r#"
 #!/usr/bin/env bash
```

**Comment by MaxVerevkin** [comment]
> This patch "fixes" the issue but only if a clipboard manager (like `clipmon`) is running

Here the delay gives the clipboard manager a chance to copy the text into it's buffer. I truly don't understand how it works for everyone except me :eyes:

**Comment by zeenix** [comment]
> Using either Wayland and X11, the clipboard and its content is “hosted” inside of the application that last put data onto it. This means that when the last Clipboard instance is dropped, the contents may become unavailable to other apps. See [SetExtLinux](https://docs.rs/arboard/latest/arboard/trait.SetExtLinux.html) for more details.

Hmm.. I don't know how arboard works but I would have thought the application in this case would be the terminal itself, not `gimoji` process. But I guess my assumption is wrong.

> I truly don't understand how it works for everyone except me eyes

Maybe you just have a much faster machine/terminal? :thinking:

**Comment by zeenix** [comment]
> > I truly don't understand how it works for everyone except me eyes
> 
> Maybe you just have a much faster machine/terminal? 🤔

Or the other way around.

Anyway, thanks for looking into this. Could you turn the patch into a PR please?
