### ISSUE TITLE
gimoji doesn't handle light themes

### ISSUE THREAD

**Issue by whot** [zeenix/gimoji#40]
A screenshot says more than a multitude of words:

![screenshot](https://github.com/zeenix/gimoji/assets/1487352/9dbde59a-b568-463a-abd0-f1e957435097)

Reproducible in [kitty](https://sw.kovidgoyal.net/kitty/) and gnome-terminal in Light theme, gnome-console has a slightly different theme so the light grey is *just* visible. Some squinting may be required.

**Comment by zeenix** [comment]
OMG. :scream: I wonder if ratatui provides some help for this.
