### ISSUE TITLE
Outdated lockfile

### ISSUE THREAD

**Issue by a-kenji** [zeenix/gimoji#43]
[Rust Book FAQ](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

Please update the lock file prior to tagging, so the package can be built using `cargo.lock`. Currently this is not possible.

**Comment by zeenix** [comment]
Oops. Most of my Rust releasing so far had been for libraries (99%) so I hope it's understandable that I made this mistake.

I'll fix, re-tag/release but unfortunately can't fix the cargo release so I'll just roll-out another release.

**Comment by a-kenji** [comment]
No problem, thank you!
